FROM node:9.6

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies first (cache as docker layer)
COPY ./ ./
RUN yarn --pure-lockfile

EXPOSE 3000
CMD [ "yarn", "dev" ]
