FROM node:8.9-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies first (cache as docker layer)
COPY package.json yarn.lock .babelrc .env.example src .eslintrc.js .flowconfig ./
RUN yarn --pure-lockfile

EXPOSE 3000
CMD [ "yarn", "dev" ]
